export { default as mario } from "./mario.png"
export { default as donkeyKong } from "./donkey-kong.png"
export { default as link } from "./link.png"
export { default as samus } from "./samus.png"
export { default as yoshi } from "./yoshi.png"
